### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by sukima** [lazd/Pinky#1]
I am interested in embedding the Pinky source into my own project.

I am writing a single file module for a Titanium project. This file I wish to release to the community free of charge and of license. I don't mind offering attribution but I do mind forcing a license on those who use it.

I originally looked into pinkySwear as it was release as a Creative Commons public license. Unfortunately, it is not Promise/A+ 2.0 compatible.

My needs also require heavy modification to the promise code (I need to add features and my own API to it). Considering I would be maintaining this I'm essentially asking to copy, paste, modify, release to the public.

I do not know enough of the BSD license or copyright to know if this is acceptable. Can you take BSD licensed code and make it your own?

Thanks for some advice.

**Comment by lazd** [comment]
I'm not a lawyer, so I'm not entirely sure whether the use you described would violate the terms of the BSD license. I'll ask around and see what I can find out. I'm also open to changing the license. As Pinky is meant to be an academic example, all I want from it is attribution.

I am curious what features and API you need to add. Could you consume Pinky and provide a wrapper around it that exposed the features and API you need? If you can't wrap it, is it possible for you to extend Pinky instead of copying and modify it? Pinky is just a constructor and all of its methods are on the prototype, so it should be very easy to extend and customize. 

With either of the above approaches, you would be able to easily upgrade when Pinky is updated.

**Comment by lazd** [comment]
@sukima, did you end up doing anything with this?

**Comment by sukima** [comment]
I ended up embedding the [then/promise](https://github.com/then/promise) implementation and heavily modifying it to suite my needs. It satisfied the Promise/A+ requirements and was licensed as MIT which was more permissive at the time.

Ultimately the decision was more about timing. While I was looking into this one, then/promise was already Promise/A+ compliant and I didn't need to manipulate the core too much.
